kind: pipeline
type: kubernetes
name: linux

platform:
  arch: amd64
  os: linux

steps:
- name: wait-for-images
  image: ya7ya/wait-for-docker:latest
  commands:
  - /wait-for-it.sh -h livepeer/go-livepeer -p ${DRONE_COMMIT_SHA:0:8} -t 60 -r 30
- name: broadcaster
  group: test
  detach: true
  image: livepeer/go-livepeer:${DRONE_COMMIT_SHA:0:8}
  settings:
    digest: ${DRONE_COMMIT_SHA:0:8}
  when:
    branch:
      exclude:
      - master
  depends_on:
  - wait-for-images
  commands:
  - /usr/bin/livepeer -broadcaster -network offchain -maxSessions=200 -rtmpAddr=localhost:1935 -cliAddr=localhost:7935 -httpAddr=localhost:8935 -orchAddr=localhost:8936 -monitor=true -transcodingOptions=P240p30fps16x9,P360p30fps16x9,P576p30fps16x9,P720p30fps16x9 -v=9
- name: orchestrator
  group: test
  detach: true
  image: livepeer/go-livepeer:${DRONE_COMMIT_SHA:0:8}
  settings:
    digest: ${DRONE_COMMIT_SHA:0:8}
  when:
    branch:
      exclude:
      - master
  depends_on:
  - wait-for-images
  environment:
    NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    NVIDIA : 0,1,2,3,4,5,6,7
    DRONE_RESOURCE_LIMIT_GPU: "4"
  commands: 
  - /usr/bin/livepeer -v=9 -orchestrator -network offchain -transcoder -monitor=true -cliAddr=localhost:7936 -httpAddr=localhost:8936 -serviceAddr=localhost:8936 -maxSessions=80 -nvidia=0,1,2,3
  resources:
    limits:
      nvidia.com/gpu: 4
- name: broadcaster-master
  group: test
  detach: true
  image: livepeer/go-livepeer:master
  when:
    branch:
      - master
  depends_on:
  - wait-for-images
  commands:
  - /usr/bin/livepeer -broadcaster -network offchain -maxSessions=200 -rtmpAddr=localhost:1935 -cliAddr=localhost:7935 -httpAddr=localhost:8935 -orchAddr=localhost:8936 -monitor=true -transcodingOptions=P240p30fps16x9,P360p30fps16x9,P576p30fps16x9,P720p30fps16x9 -v=9
- name: orchestrator-master
  group: test
  detach: true
  image: livepeer/go-livepeer:master
  when:
    branch:
      - master
  depends_on:
  - wait-for-images
  environment:
    NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    NVIDIA : 0,1,2,3,4,5,6,7
    DRONE_RESOURCE_LIMIT_GPU: "4"
  commands: 
  - /usr/bin/livepeer -v=9 -orchestrator -network offchain -transcoder -monitor=true -cliAddr=localhost:7936 -httpAddr=localhost:8936 -serviceAddr=localhost:8936 -maxSessions=80 -nvidia=0,1,2,3
  resources:
    limits:
      nvidia.com/gpu: 4
- name: build
  image: golang:1.13
  environment:
      PKG_CONFIG_PATH: /root/compiled/lib/pkgconfig
      GOPATH: /go
      DOCKER_CLI_EXPERIMENTAL: enabled
  commands:
  - pwd
  - echo $DRONE_TARGET_BRANCH $DRONE_COMMIT_SHA
  - cd /drone/src
  - wget https://storage.googleapis.com/lp_testharness_assets/official_test_source_2s_keys_24pfs_3min.mp4
- name: stream-tester
  group: test
  image: ya7ya/stream-tester:latest
  depends_on:
  - wait-for-images
  - orchestrator
  - broadcaster
  environment:
    GODEBUG: http2client=0
    DISCORD_WEBHOOK_URL:
      from_secret: discord_webhook_url
    DISCORD_WEBHOOK_USER:
      from_secret: discord_webhook_user
  commands:
    - /root/streamtester -no-bar -latency  -host 'localhost' -rtmp 1935 -media 8935 -profiles '4' -v '1' -file=/drone/src/official_test_source_2s_keys_24pfs_3min.mp4 -stats-file /drone/src/stream_tester_result.json -discord-url $DISCORD_WEBHOOK_URL -discord-user-name $DISCORD_WEBHOOK_USER
- name: result
  image: golang:1.13
  depends_on:
  - stream-tester
  commands:
  - cat /drone/src/stream_tester_result.json
  